-- 1. Top 3 Most Played Songs
SELECT
	T.TITLE,
	COUNT(*) AS PLAY_COUNT
FROM
	LISTENING_HISTORY LH
	JOIN TRACKS T ON LH.TRACK_ID = T.TRACK_ID 
GROUP BY
	T.TITLE
ORDER BY
	PLAY_COUNT DESC
LIMIT
	3;

-- 2. Top 5 Artists by Play Count
SELECT
	A.ARTIST_NAME,
	COUNT(*) AS TOTAL_PLAYS
FROM
	LISTENING_HISTORY LH
	JOIN TRACKS T ON LH.TRACK_ID = T.TRACK_ID
	JOIN ARTISTS A ON T.ARTIST_ID = A.ARTIST_ID
GROUP BY
	A.ARTIST_NAME
ORDER BY
	TOTAL_PLAYS DESC
LIMIT
	5;

-- 3. Total Listening Time by Each User (including 0 plays)
SELECT
	U.NAME,
	ROUND(SUM(T.DURATION_SEC) / 60.0, 2) AS TOTAL_LISTENING_MINS
FROM
	USERS U
	LEFT JOIN LISTENING_HISTORY LH ON LH.USER_ID = U.USER_ID
	LEFT JOIN TRACKS T ON LH.TRACK_ID = T.TRACK_ID
GROUP BY
	U.USER_ID
ORDER BY
	TOTAL_LISTENING_MINS DESC;

-- 4. Monthly Play Trends
SELECT
	DATE_TRUNC('month', LISTEN_DATE) AS MONTH,
	COUNT(*) AS TOTAL_PLAYS
FROM
	LISTENING_HISTORY
GROUP BY
	MONTH
ORDER BY
	MONTH;

-- 5. Skipped Songs (played < 60% of duration)
SELECT
	T.TITLE,
	U.NAME,
	LH.PLAY_DURATION_SEC,
	T.DURATION_SEC
FROM
	LISTENING_HISTORY LH
	JOIN TRACKS T ON LH.TRACK_ID = T.TRACK_ID
	JOIN USERS U ON LH.USER_ID = U.USER_ID
WHERE
	LH.PLAY_DURATION_SEC < T.DURATION_SEC * 0.6;

-- 6. Users Who Fully Completed Songs (100% Playback) with All Track Titles
SELECT
	U.NAME AS USER_NAME,
	STRING_AGG(T.TITLE, ', ') AS TRACK_TITLES_COMPLETED
FROM
	LISTENING_HISTORY LH
	JOIN USERS U ON LH.USER_ID = U.USER_ID
	JOIN TRACKS T ON LH.TRACK_ID = T.TRACK_ID
WHERE
	LH.PLAY_DURATION_SEC = T.DURATION_SEC
GROUP BY
	U.NAME
ORDER BY
	U.NAME;

-- 7. Users Who Listened to All Songs by an Artist
SELECT
	U.NAME AS USER_NAME,
	A.ARTIST_NAME
FROM
	USERS U
	JOIN ARTISTS A ON 1 = 1
WHERE
	NOT EXISTS (
		SELECT
			1
		FROM
			TRACKS T
		WHERE
			T.ARTIST_ID = A.ARTIST_ID
		EXCEPT
		SELECT
			T2.TRACK_ID
		FROM
			LISTENING_HISTORY LH2
			JOIN TRACKS T2 ON LH2.TRACK_ID = T2.TRACK_ID
		WHERE
			LH2.USER_ID = U.USER_ID
			AND T2.ARTIST_ID = A.ARTIST_ID
	)
ORDER BY
	A.ARTIST_NAME,
	U.NAME;

-- 8. Peak Listening Day (Date with Most Total Plays)
SELECT
	LISTEN_DATE,
	COUNT(*) AS TOTAL_PLAYS
FROM
	LISTENING_HISTORY
GROUP BY
	LISTEN_DATE
ORDER BY
	TOTAL_PLAYS DESC
LIMIT
	1;
​
